FROM bellsoft/liberica-openjdk-alpine:11
ARG TOKEN_ARG
ARG MYSQL_HOST_ARG
ARG MYSQL_PORT_ARG
ARG MYSQL_DB_ARG
ARG DB_USER_ARG
ARG DB_PASS_ARG
ENV MYSQL_HOST=$MYSQL_HOST_ARG
ENV MYSQL_PORT=$MYSQL_PORT_ARG
ENV MYSQL_DB=$MYSQL_DB_ARG
ENV DB_USER=$DB_USER_ARG
ENV DB_PASS=$DB_PASS_ARG
ENV TOKEN=$TOKEN_ARG

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]
